export const FI = {
	common: {
		close: "Sulje",
		back: "Takaisin",
		settings: "Oma mukavuusalue",
		reducedMotion: "Vähennä animaatioita",
		dialogLabel: "Lisätiedot",
	},
	brand: {
		logoLabel: "Örkkipokka etusivu",
		first: "ÖRKKI",
		second: "POKKA",
	},
	documentTitle: "Örkkipokka — älä luota kehenkään",
	rules: {
		title: "Kusetuksen lyhyt oppimäärä",
		steps: [
			"Valitse kortti, uhri ja örkki, jota väität kortin esittävän. Totuus on vapaaehtoinen.",
			"Vastaanottaja valitsee Uskon tai En usko. Oikea arvio antaa kortin lähettäjälle, väärä arvio arvaimelle.",
			"Voit myös katsoa kortin ja siirtää sen eteenpäin uuden väitteen kera. Viimeinen pelaaja joutuu aina vastaamaan.",
			"Neljä samaa örkkiä pöydässäsi: hävisit. Samoin käy, jos sinun pitäisi aloittaa, mutta kätesi on tyhjä.",
			"Kaksinpelissä poistetaan 10 korttia, jaetaan 27 kummallekin ja tappioraja on viisi korttia. Ei siirtämistä.",
		],
		visibility: "Muiden kädet ovat salaisia. Pöydän kortit, käsien koot ja kortin kulkureitti näkyvät kaikille. Sivusta voit arvata väitteen totuutta: oikea arvaus tuo lisäpisteen.",
		videoCall: "Avaa videopuhelu oheen (Discord, Meet, Teams). Pidä naama näkyvissä ja selitykset uskottavina.",
	},
	landing: {
		rulesButton: "Miten pelataan? ↗",
		eyebrow: "2–6 ystävää. 64 korttia. Selkäänpuukotus sisältyy hintaan.",
		headingFirst: "Huonoja kortteja.",
		headingEmphasis: "Vielä huonompia",
		headingLast: "ystäviä.",
		lede: "Örkki vai täyttä paskaa? Lue kavereidesi naamoja, siirrä ongelma eteenpäin ja pidä oma pokkasi.",
		joinLabel: "Millä nimellä sinua kirotaan?",
		namePlaceholder: "Nimesi pöydässä",
		join: "Liity pöytään ↗",
		accountNote: "Ei tiliä. Ei salasanaa. Vain kavereiden kutsulinkki.",
		creatingRoom: "Avataan pöytää…",
		createRoom: "Perusta oma pöytä ↗",
		resumeRoom: "Palaa aiempaan huoneeseen",
		privacyNote: "Yksityinen huone · selkäänpuukotuspeli · aikuisille",
		backCard: "LUPAAN, ETTEI SE PURE.",
		frontCard: "LUOTA MINUUN.",
		cardSerial: "01 / 08 — EPÄILYTTÄVÄ ÖRKKI",
		stampFirst: "100%",
		stampSecond: "EPÄLUOTETTAVA",
		footerLeft: "POKKA PITÄÄ. YSTÄVYYS EI.",
		footerRight: "Puhelu muualla. Kusetus täällä.",
	},
	error: {
		createRoom: "Huoneen luominen epäonnistui.",
		connection: "Yhteys epäonnistui.",
		serverUnavailable: "Palvelimeen ei saada yhteyttä. Yritetään uudelleen…",
		commandTimeout: "Vastausta ei saatu. Tarkista päivittynyt pelitilanne ennen uutta toimintoa.",
		copyLink: (url: string) => `Kopioi osoite selaimen osoiteriviltä: ${url}`,
	},
	session: {
		replacedTitle: "Paikkasi on käytössä toisella laitteella.",
		replacedBody: "Tämä laite ei enää ohjaa peliä.",
		returnToJoin: "Palaa liittymissivulle",
		searchingRoom: "Etsitään pöytää…",
		muted: "Äänet päälle",
		mute: "Mykistä äänet",
		mutedShort: "♪ pois",
		soundOn: "♪ päällä",
		soundLabel: "Äänet",
		rules: "Säännöt",
		history: "Historia",
		privateTable: "YKSITYINEN PÖYTÄ",
		reconnecting: "YHTEYS KATKENNUT — YHDISTETÄÄN",
		linkCopied: "Linkki kopioitu ✓",
		copyInvite: "Kopioi kutsulinkki ↗",
		connectionLost: "Yhteys katkesi. Paikkasi ja korttisi ovat tallessa.",
		approve: "Hyväksy",
		reject: "Hylkää",
		requestSeat: (name: string) => `${name} pyytää paikkaa.`,
		approvals: (current: number, required: number) => `${current}/${required} hyväksyntää`,
		replacementNeeded: "Tarvitaan korvaava pelaaja.",
		waitingReplacement: "Paikka ja kortit odottavat. Jaa kutsulinkki.",
		confirmEnd: "Päätetäänkö peli ilman häviäjää?",
		endGame: "Päätä peli",
		stopGame: "Keskeytä peli",
		focusMode: "Koko näyttö",
		exitFocusMode: "Poistu koko näytöstä",
		gameEnded: "Jatketaan paremmalla porukalla.",
	},
	lobby: {
		eyebrow: "KUTSU KAVERIT. VALMISTELE POKKA.",
		heading: "Pöytä on katettu.",
		lede: "Avaa videopuhelu muualla. Kun kaikki ovat valmiina, kortit puhuvat puolestaan.",
		readyState: "Valmis kusetukseen",
		notReadyState: "Kerää rohkeutta",
		offline: "Yhteys katkennut",
		self: " (sinä)",
		readyButton: "En sittenkään ole valmis",
		notReadyButton: "Olen valmis — ja epäilyttävä",
		sit: "Istu pöytään",
		stand: "Siirry katsojaksi",
		leaveTable: "Poistu pöydästä",
		leaveConfirm: "Poistutaanko pöydästä? Sinun asemasi poistetaan aulasta.",
		countdown: "Kohta on myöhäistä katua.",
		quote: "“Tämä on ihan varmasti örkki.”",
		guide: "Opasta ensimmäisellä vuorollani",
		preferencesNote: "Valinnat muistetaan tällä laitteella.",
		spectators: (count: number) => `${count} katsojaa · 2–6 pelaajaa`,
		spectatorsHeading: "Katsojat",
		spectatorsEmpty: "Ei katsojia vielä.",
		computer: "Tietokone",
		addComputer: "Lisää tietokonepelaaja",
		closeLobby: "Poista aula",
		closeConfirm: "Poistetaanko aula pysyvästi? Kaikki pelaajat katkaistaan ja kutsulinkki lakkaa toimimasta.",
		remove: "Poista",
		removeConfirm: "Poistetaanko tämä pelaaja pöydästä?",
		removeComputer: (name: string) => `Poista ${name}`,
		removeComputerConfirm: (name: string) => `Poistetaanko ${name} pöydästä?`,
	},
	table: {
		eyebrow: "PIDÄ POKKASI",
		endedHeading: "Se oli siinä.",
		activeHeading: "Kaikki näyttävät syyllisiltä.",
		threshold: (count: number) => `${count} samaa = örkkikanta räjähti`,
		self: " · sinä",
		removed: "Poistettu",
		thinking: "Punoo valhetta…",
		handCount: (count: number) => `${count} korttia kädessä`,
		cleanTable: "Ei vielä örkkejä pöydässä.",
		confirmRemove: "Poistetaanko pelaaja ja jaetaanko kortit? Jos jäljelle jäisi alle kolme pelaajaa, odotetaan korvaajaa.",
		removeAndDeal: "Poista / jaa kortit",
		requestSeat: "Pyydä paikkaa",
		loser: "ILLAN EPÄONNISTUJA",
		cancelled: "PELI KESKEYTETTY",
		noLoser: "Ei häviäjää.",
		matchingLoss: (count: number) => `${count} samaa örkkiä. Luonto voitti.`,
		emptyHandLoss: "Tyhjä käsi, kylmä perse.",
		rematch: "Uusi peli — sama kutsulinkki ↗",
		endPlaying: "Lopeta pelaaminen",
		endPlayingConfirm: "Lopetetaanko pelaaminen? Aula poistetaan ja kaikki pelaajat katkaistaan.",
		claimOnTable: "VÄITE ON PÖYDÄSSÄ",
		claimCard: "VÄITE",
		nextMove: "SEURAAVA SIIRTO",
		cardBack: "ÄLÄ LUOTA KEHENKÄÄN.",
		routeLabel: "Kortin kulkureitti",
		claim: (creature: string) => `“Tämä on ${creature}.”`,
		startTurn: (name: string) => `${name}, anna palaa.`,
		startPrompt: "Valitse kortti, uhri ja uskottava selitys.",
		cancelledRound: "Kierros peruttiin. Kortti poistettiin näkyvästi.",
		takesCard: (name: string) => `${name} ottaa kortin.`,
		nextPlayer: (name: string) => `Seuraavana: ${name}`,
		startHint: "Valitse omista korteista örkki, sitten kohde ja väite. Vain Lähetä paljastaa väitteen muille.",
		responseHint: "Uskon = väite pitää paikkansa. En usko = se on valhe. Katso ja siirrä sitoo sinut siirtämään kortin.",
		dismissHint: "Selvä, pokka pitää ✕",
		secretPrediction: "Sivustakatsojan veikkaus",
		predictionReveal: "Paljastetaan vasta kortin ratkettua.",
		believe: "Uskon",
		disbelieve: "En usko",
		previousRound: "Edellinen kortti ja lukitut arvaukset",
		retiredCards: (count: number) => `Poistetut näkyvät kortit (${count})`,
	},
	actions: {
		ownHand: "OMA KÄTESI · VAIN SINÄ NÄET NÄMÄ",
		spectatorHand: "KATSOMOSSA · VAIN JULKINEN TIETO",
		emptyHand: "Käsi on tyhjä. Et saa joutua aloittamaan seuraavaa kierrosta.",
		targetLabel: "2. Kenelle?",
		cardStep: "1. Valitse kortti",
		cardPrompt: "Klikkaa yhtä oman kätesi korteista",
		targetLabelPassing: "Kenelle siirrät?",
		targetAria: "Kohdepelaaja",
		chooseTarget: "Valitse uhri",
		clickTarget: "Klikkaa kohdepelaajaa pöydästä",
		choosePlayer: (name: string) => `Valitse ${name} kohdepelaajaksi`,
		claimLabel: "3. Mitä väität?",
		claimTo: (name: string) => `Valittu kohde: ${name}`,
		changeTarget: "Vaihda kohdetta",
		claimAria: "Väitetty örkki",
		chooseCreature: "Valitse örkki",
		trueChoice: "Tosi kortti",
		chooseClaim: "Valitse väite",
		chooseBluff: "Valitse bluffi",
		chooseTruth: "Valitse oikea kortti",
		clickAgain: "Klikkaa uudelleen",
		pass: "Siirrä kortti ↗",
		send: "Lähetä kortti ↗",
		lastPlayer: "Olet viimeinen. Et voi enää siirtää korttia.",
		waitingPlayer: "Lue naamoja. Seuraava kusetus voi osua sinuun.",
		waitingSpectator: "Liity seuraavaan peliin aulassa tai pyydä poissa olevan pelaajan paikkaa.",
		watchAndPass: "Katso ja laita eteenpäin",
		cardCount: (count: number) => `${count} korttia`,
	},
	round: {
		cancelled: "Kierros peruttiin; arvauksia ei paljasteta eikä pisteytetä.",
		trueClaim: "— totta",
		falseClaim: "— valhe",
		noPredictions: "Ei yleisöarvauksia.",
		correctAudienceGuesses: (correct: number, total: number) => `${correct}/${total} yleisöarvausta oikein`,
	},
	history: {
		title: "Pöydän likainen historia",
		empty: "Ei vielä päättyneitä pelejä. Anna kavereille aikaa nolata itsensä.",
		select: "Valitse peli",
		game: (number: number, date: string, loser: string) => `Peli ${number} · ${date} · ${loser}`,
		loser: (name: string) => `${name} hävisi.`,
		endedNoLoser: "Peli päättyi ilman häviäjää.",
		resolvedCards: (count: number) => `${count} ratkaistua korttia.`,
		player: "Pelaaja",
		guesses: "Vastaukset",
		bluffCalls: "“En usko”",
		ownBluffs: "Omat bluffit",
		rightWrong: "oikein / väärin",
		passedCaught: "läpi / kiinni",
		defaultPlayer: "Pelaaja",
		roundByRound: "Kierros kierrokselta",
		cancelled: "Peruttu",
		gotCard: (name: string) => `${name} otti kortin`,
		awards: {
			bluffs: { title: "Paskapuheen tohtori", copy: "Väitöskirja oli palturia. Kaikki taputtivat.", reason: (count: number) => `Eniten läpimenneitä bluffeja: ${count}.` },
			catches: { title: "Paskatutka", copy: "Hämähäkkivaistoihin verrattavissa oleva yliluonnollinen kyky haistaa kusetus.", reason: (count: number) => `Eniten käräytettyjä bluffeja: ${count}.` },
			correct: { title: "Oraakkeli peräsuolesta", copy: "Ennustukset tulivat perseestä. Silti oikein.", reason: (count: number) => `Eniten oikeita sivustakatsojan arvauksia: ${count}.` },
			chain: { title: "Saatanan kiertopalkinto", copy: "Kävi kaikilla. Jäi yhden riesaksi.", reason: (count: number) => `Hävisi pelin pisimmässä korttiketjussa: ${count} siirtoa.` },
			twice: { title: "Kuiva kakkonen", copy: "Sama kusetus. Sama uhri. Ei liukuvoidetta.", reason: "Huijasi samaa pelaajaa onnistuneesti vähintään kahdesti peräkkäin." },
			crowd: { title: "Joukkokusetus", copy: "Koko pöytä söi paskaa ja pyysi reseptin.", reason: "Bluffi meni läpi vastaanottajalle ja kaikille vähintään kahdelle arvanneelle pelaajalle." },
			paranoid: { title: "Vainoharhainen mulkku", copy: "Kukaan ei valehdellut. Sekös epäilytti.", reason: "Epäili vähintään kolmea totta väitettä väärin." },
			truth: { title: "Totuus sattuu, saatana", copy: "Kerrankin puhuit totta. Kaveri maksoi siitä.", reason: "Sai vähintään kolme totta väitettä näyttämään valheilta." },
			undertaker: { title: "Hautausurakoitsija", copy: "Toimitus perille. Asiakas kylmänä.", reason: "Syötti läpimenneen bluffin, joka aiheutti vastaanottajan tappion." },
			"own-grave": { title: "Oma kusetus, oma kuoppa", copy: "Kaivoit kuopan. Hyppäsit itse.", reason: "Jäi kiinni bluffista, joka aiheutti oman tappion." },
			grave: { title: "Hautapaikka varattu", copy: "Arkkuun sai jo kaivertaa nimen.", reason: "Kävi yhden kortin päässä tappiosta ja selviytyi vielä vähintään kolme kierrosta." },
			empty: { title: "Tyhjä käsi, kylmä perse", copy: "Eväät loppuivat ennen selityksiä.", reason: "Hävisi, koska käsi oli tyhjä oman aloitusvuoron alkaessa." },
		},
	},
	footer: "ÖRKKIPOKKA",
} as const;
