export const FI = {
	common: {
		close: "Sulje",
		back: "Takaisin",
		settings: "Oma mukavuusalue",
		reducedMotion: "Vähennä animaatioita",
		dialogLabel: "Lisätiedot",
	},
	brand: {
		logoLabel: "Örkkipokka etusivu",
		first: "ÖRKKI",
		second: "POKKA",
	},
	documentTitle: "Örkkipokka — älä luota kehenkään",
	rules: {
		title: "Kusetuksen lyhyt oppimäärä",
		steps: [
			"Valitse kortti, uhri ja örkki, jota väität kortin esittävän. Totuus on vapaaehtoinen.",
			"Vastaanottaja valitsee Uskon tai En usko. Oikea arvio antaa kortin lähettäjälle, väärä arvio arvaimelle.",
			"Voit myös katsoa kortin ja siirtää sen eteenpäin uuden väitteen kera. Viimeinen pelaaja joutuu aina vastaamaan.",
			"Neljä samaa örkkiä pöydässäsi: hävisit. Samoin käy, jos sinun pitäisi aloittaa, mutta kätesi on tyhjä.",
			"Kaksinpelissä poistetaan 10 korttia, jaetaan 27 kummallekin ja tappioraja on viisi korttia. Ei siirtämistä.",
		],
		visibility: "Muiden kädet ovat salaisia. Pöydän kortit, käsien koot ja kortin kulkureitti näkyvät kaikille. Sivusta voit arvata väitteen totuutta: oikea arvaus tuo lisäpisteen.",
		videoCall: "Avaa videopuhelu oheen (Discord, Meet, Teams). Pidä naama näkyvissä ja selitykset uskottavina.",
	},
	landing: {
		rulesButton: "Miten pelataan? ↗",
		eyebrow: "2–6 ystävää. 64 korttia. Selkäänpuukotus sisältyy hintaan.",
		headingFirst: "Huonoja kortteja.",
		headingEmphasis: "Vielä huonompia",
		headingLast: "ystäviä.",
		lede: "Örkki vai täyttä paskaa? Lue kavereidesi naamoja, siirrä ongelma eteenpäin ja pidä oma pokkasi.",
		joinLabel: "Millä nimellä sinua kirotaan?",
		namePlaceholder: "Nimesi pöydässä",
		join: "Liity pöytään ↗",
		accountNote: "Ei tiliä. Ei salasanaa. Vain kavereiden kutsulinkki.",
		creatingRoom: "Avataan pöytää…",
		createRoom: "Perusta oma pöytä ↗",
		resumeRoom: "Palaa aiempaan huoneeseen",
		privacyNote: "Avoin aula oletuksena · selkäänpuukotuspeli · aikuisille",
		openRooms: "Avoimet pöydät",
		hostRoom: (name: string) => `${name}n pöytä`,
		roomPlayers: (count: number) => `${count}/6 pelaajaa`,
		roomPlaying: "Peli käynnissä · liity katsojaksi",
		roomLobby: "Aulassa · liity pelaamaan",
		backCard: "LUPAAN, ETTEI SE PURE.",
		frontCard: "LUOTA MINUUN.",
		cardSerial: "01 / 08 — EPÄILYTTÄVÄ ÖRKKI",
		stampFirst: "100%",
		stampSecond: "EPÄLUOTETTAVA",
		footerLeft: "POKKA PITÄÄ. YSTÄVYYS EI.",
		footerRight: "Puhelu muualla. Kusetus täällä.",
	},
	error: {
		createRoom: "Huoneen luominen epäonnistui.",
		connection: "Yhteys epäonnistui.",
		serverUnavailable: "Palvelimeen ei saada yhteyttä. Yritetään uudelleen…",
		commandTimeout: "Vastausta ei saatu. Tarkista päivittynyt pelitilanne ennen uutta toimintoa.",
		copyLink: (url: string) => `Kopioi osoite selaimen osoiteriviltä: ${url}`,
	},
	session: {
		replacedTitle: "Paikkasi on käytössä toisella laitteella.",
		replacedBody: "Tämä laite ei enää ohjaa peliä.",
		returnToJoin: "Palaa liittymissivulle",
		searchingRoom: "Etsitään pöytää…",
		muted: "Äänet päälle",
		mute: "Mykistä äänet",
		mutedShort: "♪ pois",
		soundOn: "♪ päällä",
		soundLabel: "Äänet",
		musicLabel: "Musiikki",
		rules: "Säännöt",
		history: "Historia",
		privateTable: "YKSITYINEN PÖYTÄ",
		openTable: "AVOIN PÖYTÄ",
		reconnecting: "YHTEYS KATKENNUT — YHDISTETÄÄN",
		linkCopied: "Linkki kopioitu ✓",
		copyInvite: "Kopioi kutsulinkki ↗",
		connectionLost: "Yhteys katkesi. Paikkasi ja korttisi ovat tallessa.",
		approve: "Hyväksy",
		reject: "Hylkää",
		requestSeat: (name: string) => `${name} pyytää paikkaa.`,
		approvals: (current: number, required: number) => `${current}/${required} hyväksyntää`,
		replacementNeeded: "Tarvitaan korvaava pelaaja.",
		waitingReplacement: "Paikka ja kortit odottavat. Jaa kutsulinkki.",
		confirmEnd: "Päätetäänkö peli ilman häviäjää?",
		endGame: "Päätä peli",
		stopGame: "Keskeytä peli",
		focusMode: "Koko näyttö",
		exitFocusMode: "Poistu koko näytöstä",
		more: "Lisää",
		gameEnded: "Jatketaan paremmalla porukalla.",
	},
	lobby: {
		eyebrow: "KUTSU KAVERIT. VALMISTELE POKKA.",
		heading: "Pöytä on katettu.",
		lede: "Avaa videopuhelu muualla. Kun kaikki ovat valmiina, kortit puhuvat puolestaan.",
		readyState: "Valmis kusetukseen",
		notReadyState: "Kerää rohkeutta",
		offline: "Yhteys katkennut",
		self: " (sinä)",
		readyButton: "En sittenkään ole valmis",
		notReadyButton: "Olen valmis — ja epäilyttävä",
		sit: "Istu pöytään",
		stand: "Siirry katsojaksi",
		leaveTable: "Poistu pöydästä",
		leaveConfirm: "Poistutaanko pöydästä? Sinun asemasi poistetaan aulasta.",
		countdown: "Kohta on myöhäistä katua.",
		quote: "“Tämä on ihan varmasti örkki.”",
		guide: "Opasta ensimmäisellä vuorollani",
		theme: "Peliteema",
		themeSelected: "✓ VALITTU",
		moreThemes: "Lisää teemoja tulossa",
		hostChoosesTheme: "Isäntä valitsee illan kortit.",
		themeLocked: "Teema lukittui lähtölaskennan ajaksi.",
		openRoom: "Näytä aula avoimena etusivulla",
		openRoomNote: "Avoimeen aulaan voi liittyä ilman kutsulinkkiä. Muut asetukset muistetaan tällä laitteella.",
		preferencesNote: "Valinnat muistetaan tällä laitteella.",
		spectators: (count: number) => `${count} katsojaa · 2–6 pelaajaa`,
		spectatorsHeading: "Katsojat",
		spectatorsEmpty: "Ei katsojia vielä.",
		computer: "Tietokone",
		addComputer: "Lisää tietokonepelaaja",
		closeLobby: "Poista aula",
		closeConfirm: "Poistetaanko aula pysyvästi? Kaikki pelaajat katkaistaan ja kutsulinkki lakkaa toimimasta.",
		remove: "Poista",
		removeConfirm: "Poistetaanko tämä pelaaja pöydästä?",
		removePlayer: (name: string) => `Poista ${name}`,
		removePlayerConfirm: (name: string) => `Poistetaanko ${name} pöydästä?`,
	},
	table: {
		eyebrow: "PIDÄ POKKASI",
		endedHeading: "Se oli siinä.",
		activeHeading: "Kaikki näyttävät syyllisiltä.",
		threshold: (count: number) => `${count} samaa = örkkikanta räjähti`,
		self: " · sinä",
		removed: "Poistettu",
		thinking: "Punoo valhetta…",
		handCount: (count: number) => `${count} korttia kädessä`,
		cleanTable: "Ei vielä örkkejä pöydässä.",
		confirmRemove: "Poistetaanko pelaaja ja jaetaanko kortit? Jos jäljelle jäisi alle kolme pelaajaa, odotetaan korvaajaa.",
		removeAndDeal: "Poista / jaa kortit",
		requestSeat: "Pyydä paikkaa",
		loser: "ILLAN EPÄONNISTUJA",
		cancelled: "PELI KESKEYTETTY",
		noLoser: "Ei häviäjää.",
		matchingLoss: (count: number) => `${count} samaa örkkiä. Luonto voitti.`,
		emptyHandLoss: "Tyhjä käsi, kylmä perse.",
		rematch: "Uusi peli — sama kutsulinkki ↗",
		endPlaying: "Lopeta pelaaminen",
		endPlayingConfirm: "Lopetetaanko pelaaminen? Aula poistetaan ja kaikki pelaajat katkaistaan.",
		claimOnTable: "VÄITE ON PÖYDÄSSÄ",
		claimCard: "VÄITE",
		nextMove: "SEURAAVA SIIRTO",
		cardBack: "ÄLÄ LUOTA KEHENKÄÄN.",
		claim(name: string, creature: string, changed?: boolean) {
			const capitalizedCreature = creature.charAt(0).toLocaleUpperCase("fi") + creature.slice(1);
			const statement = changed === undefined ? `tämä on ${capitalizedCreature}` : changed ? `eiku se on ${capitalizedCreature}` : `olihan se ${capitalizedCreature}`;
			return `${name} sanoo: ${statement}.`;
		},
		claimRecipient: "puheet",
		startTurn: (name: string) => `${name}, anna palaa.`,
		startPrompt: "Valitse kortti, uhri ja uskottava selitys.",
		cancelledRound: "Kierros peruttiin. Kortti poistettiin näkyvästi.",
		takesCard: (name: string) => `${name} ottaa kortin.`,
		nextPlayer: (name: string) => `${name}!`,
		yourTurn: "Sun puheet!",
		startHint: "Valitse omista korteista örkki, sitten kohde ja väite. Vain Lähetä paljastaa väitteen muille.",
		responseHint: "Uskon = väite pitää paikkansa. En usko = se on valhe. Katso ja siirrä sitoo sinut siirtämään kortin.",
		dismissHint: "Selvä, pokka pitää ✕",
		tutorialTitle: "Pieni peliohje",
		secretPrediction: "Sivustakatsojan veikkaus",
		predictionReveal: "Paljastetaan vasta kortin ratkettua.",
		believe: "Uskon",
		disbelieve: "En usko",
		believed: (name: string) => `${name} uskoi`,
		disbelieved: (name: string) => `${name} ei uskonut`,
		previousRound: "Edellinen kortti ja lukitut arvaukset",
		retiredCards: (count: number) => `Poistetut näkyvät kortit (${count})`,
	},
	actions: {
		ownHand: "OMA KÄTESI · VAIN SINÄ NÄET NÄMÄ",
		spectatorHand: "KATSOMOSSA · VAIN JULKINEN TIETO",
		emptyHand: "Käsi on tyhjä. Et saa joutua aloittamaan seuraavaa kierrosta.",
		targetLabel: "2. Kenelle?",
		cardStep: "1. Valitse kortti",
		cardPrompt: "Klikkaa yhtä oman kätesi korteista",
		targetLabelPassing: "Kenelle siirrät?",
		targetAria: "Kohdepelaaja",
		chooseTarget: "Valitse uhri",
		clickTarget: "Klikkaa kohdepelaajaa pöydästä",
		choosePlayer: (name: string) => `Valitse ${name} kohdepelaajaksi`,
		claimLabel: "3. Mitä väität?",
		claimTo: (name: string) => `Valittu kohde: ${name}`,
		changeTarget: "Vaihda kohdetta",
		claimAria: "Väitetty örkki",
		chooseCreature: "Valitse örkki",
		trueChoice: "Tosi kortti",
		chooseClaim: "Valitse väite",
		chooseBluff: "Valitse bluffi",
		chooseTruth: "Valitse oikea kortti",
		clickAgain: "Klikkaa uudelleen",
		pass: "Siirrä kortti ↗",
		send: "Lähetä kortti ↗",
		lastPlayer: "Olet viimeinen. Et voi enää siirtää korttia.",
		waitingPlayer: "Lue naamoja. Seuraava kusetus voi osua sinuun.",
		waitingSpectator: "Liity seuraavaan peliin aulassa tai pyydä poissa olevan pelaajan paikkaa.",
		watchAndPass: "Katso ja laita eteenpäin",
		cardCount: (count: number) => `${count} korttia`,
	},
	round: {
		cancelled: "Kierros peruttiin; arvauksia ei paljasteta eikä pisteytetä.",
		trueClaim: "— totta",
		falseClaim: "— valhe",
		noPredictions: "Ei yleisöarvauksia.",
		correctAudienceGuesses: (correct: number, total: number) => `${correct}/${total} yleisöarvausta oikein`,
	},
	history: {
		title: "Pöydän likainen historia",
		empty: "Ei vielä päättyneitä pelejä. Anna kavereille aikaa nolata itsensä.",
		select: "Valitse peli",
		game: (number: number, date: string, loser: string) => `Peli ${number} · ${date} · ${loser}`,
		loser: (name: string) => `${name} hävisi.`,
		endedNoLoser: "Peli päättyi ilman häviäjää.",
		resolvedCards: (count: number) => `${count} ratkaistua korttia.`,
		player: "Pelaaja",
		guesses: "Vastaukset",
		bluffCalls: "“En usko”",
		ownBluffs: "Omat bluffit",
		rightWrong: "oikein / väärin",
		passedCaught: "läpi / kiinni",
		defaultPlayer: "Pelaaja",
		roundByRound: "Kierros kierrokselta",
		showMore: (remaining: number) => `Näytä lisää (${Math.min(10, remaining)})`,
		cancelled: "Peruttu",
		gotCard: (name: string) => `${name} otti kortin`,
		awards: {
			bluffs: { title: "Paskapuheen tohtori", copy: "Väitöskirja oli palturia. Kaikki taputtivat.", reason: (count: number) => `Yksin eniten läpimenneitä bluffeja, vähintään kolme: ${count}.` },
			catches: { title: "Paskatutka", copy: "Hämähäkkivaistoihin verrattavissa oleva yliluonnollinen kyky haistaa kusetus.", reason: (count: number) => `Yksin eniten käräytettyjä bluffeja, vähintään kolme: ${count}.` },
			correct: { title: "Oraakkeli peräsuolesta", copy: "Ennustukset tulivat perseestä. Silti oikein.", reason: (count: number) => `Yksin eniten oikeita sivustakatsojan arvauksia, vähintään viisi: ${count}.` },
			chain: { title: "Saatanan kiertopalkinto", copy: "Kävi kaikilla. Jäi yhden riesaksi.", reason: (count: number) => `Hävisi pelin pisimmässä korttiketjussa: ${count} siirtoa.` },
			twice: { title: "Kuiva kakkonen", copy: "Sama kusetus. Sama uhri. Ei liukuvoidetta.", reason: "Huijasi samaa pelaajaa onnistuneesti vähintään kolmesti peräkkäin." },
			crowd: { title: "Joukkokusetus", copy: "Koko pöytä söi paskaa ja pyysi reseptin.", reason: "Vähintään viiden pelaajan pelissä bluffi meni läpi vastaanottajalle ja kaikille kolmelle tai useammalle arvanneelle." },
			paranoid: { title: "Vainoharhainen mulkku", copy: "Kukaan ei valehdellut. Sekös epäilytti.", reason: "Epäili vähintään neljää totta väitettä väärin." },
			truth: { title: "Totuus sattuu, saatana", copy: "Kerrankin puhuit totta. Kaveri maksoi siitä.", reason: "Sai vähintään neljä totta väitettä näyttämään valheilta." },
			undertaker: { title: "Hautausurakoitsija", copy: "Toimitus perille. Asiakas kylmänä.", reason: "Syötti läpimenneen bluffin, joka aiheutti vastaanottajan tappion." },
			"own-grave": { title: "Kuset reisillä", copy: "Kasteli omat housunsa.", reason: "Jäi kiinni bluffista, joka aiheutti oman tappion." },
			grave: { title: "Hautapaikka varattu", copy: "Arkkuun sai jo kaivertaa nimen.", reason: "Kävi yhden kortin päässä tappiosta ja selviytyi vielä vähintään viisi kierrosta." },
			empty: { title: "Tyhjä käsi, kylmä perse", copy: "Eväät loppuivat ennen selityksiä.", reason: "Hävisi, koska käsi oli tyhjä oman aloitusvuoron alkaessa." },
			"poker-grave": { title: "Pokka pitää", copy: "Valehteli niin siististi, että ruumiskin nyökkäsi.", reason: "Sai vähintään viisi bluffia menemään läpi saman pelin aikana." },
			"last-bluff": { title: "Viimeinen kusetus", copy: "Valehteli vielä toinen jalka haudassa.", reason: "Onnistui bluffissa ollessaan yhden samanlaisen kortin päässä tappiosta." },
			"honest-bastard": { title: "Rehellinen paskiainen", copy: "Puhui totta niin usein, että se alkoi vaikuttaa epäilyttävältä.", reason: "Esitti vähintään seitsemän väitettä, joista jokainen oli totta." },
			"serial-liar": { title: "Sarjavalehtelija", copy: "Totuus nähtiin viimeksi alkuillasta.", reason: "Esitti kuusi omaa valheellista väitettä peräkkäin." },
			"cheap-bluff": { title: "Halpa meni läpi", copy: "Ei ollut hyvä valhe. Se vain löysi tarpeeksi tyhmän kohteen.", reason: "Vähintään viiden pelaajan pelissä bluffasi onnistuneesti, vaikka kaikki vähintään kolme ennustusta tunnistivat valheen." },
			"lie-detector": { title: "Valheenpaljastaja", copy: "Haistoi kusetuksen ennen kuin se ehti jäähtyä.", reason: "Käräytti vähintään viisi bluffia saman pelin aikana." },
			"trust-issues": { title: "Luottamusongelma", copy: "Epäili kaikkea. Kerran jopa aiheesta.", reason: "Valitsi En usko vähintään seitsemästi ja osui oikeaan korkeintaan kerran." },
			"trusting-dead": { title: "Hyväuskoinen vainaja", copy: "Luotti ystäviinsä. Siihen se sitten kuoli.", reason: "Uskoi vähintään viisi valhetta ja hävisi lopulta pelin." },
			"wrong-corpse": { title: "Väärä ruumis", copy: "Ruumiinavaus onnistui. Potilas vain oli elossa.", reason: "Epäili totuutta, kun lähettäjä oli yhden kortin päässä tappiosta." },
			optimist: { title: "Ihmiskunnan viimeinen optimisti", copy: "Uskoi kaiken. Maailma rankaisi asianmukaisesti.", reason: "Vastasi Uskon vähintään seitsemästi valitsematta kertaakaan En usko." },
			"recycle-problem": { title: "Kierrätä ongelma", copy: "Kun paska osuu käteen, anna se kaverille.", reason: "Katsoi ja siirsi kortin eteenpäin vähintään viidesti." },
			"full-circle": { title: "Täysi kierros, vajaa järki", copy: "Kortti näki kaikki pelaajat ja jäi lopulta tämän riesaksi.", reason: "Vähintään viiden pelaajan pelissä sai kortin ketjusta, jossa kortti kävi jokaisella." },
			"return-sender": { title: "Palautus lähettäjälle", copy: "Paska teki kunniakierroksen ja palasi kotiin.", reason: "Sai vähintään kolmen siirron korttiketjun lopuksi aloittamansa kortin takaisin." },
			"dirty-baton": { title: "Likainen viestikapula", copy: "Kaikki koskivat. Kukaan ei pese käsiään.", reason: "Osallistui vähintään viiteen usean siirron korttiketjuun." },
			"slow-death": { title: "Hidas kuolema", copy: "Ei hävinnyt nopeasti. Hävisi perusteellisesti.", reason: "Hävisi vähintään 25 ratkaistua korttia kestäneen pelin." },
			"clean-corpse": { title: "Puhdas ruumis", copy: "Ei bluffannut kertaakaan. Kuoli silti.", reason: "Hävisi esitettyään vähintään neljä väitettä, joista jokainen oli totta." },
			"bullet-dodger": { title: "Luodinväistäjä", copy: "Kaikki tähtäsivät. Jostain syystä tämä jäi henkiin.", reason: "Oli yksin eniten ja vähintään viiden aloitussiirron kohteena eikä hävinnyt." },
			"silent-partner": { title: "Hiljainen osakas", copy: "Oli paikalla. Juridisesti.", reason: "Selvisi vähintään kymmenen kierroksen pelistä aloittamatta väitettä tai vastaamatta yhteenkään." },
			"equal-bastard": { title: "Tasapuolinen kusipää", copy: "Kohteli kaikkia yhtä huonosti.", reason: "Vähintään neljän pelaajan pelissä lähetti kortin jokaiselle muulle aktiiviselle pelaajalle." },
			"sofa-psychologist": { title: "Sohvapsykologi", copy: "Luki ilmeitä kuin halpaa rikosromaania.", reason: "Teki vähintään kahdeksan ennustusta ja sai ne kaikki oikein." },
			"wrong-professional": { title: "Väärinymmärryksen ammattilainen", copy: "Väärässä olemisesta tuli jo elämäntapa.", reason: "Teki vähintään kahdeksan ennustusta osumatta kertaakaan oikeaan." },
			"lone-genius": { title: "Yksinäinen nero", copy: "Oli yksin oikeassa ja tiesi muutenkin muita paremmin.", reason: "Vähintään viiden pelaajan pelissä oli kolmesta tai useammasta ennustajasta ainoa oikeassa ollut ja sai ehdokkaista eniten ennustuksia oikein." },
			"herd-grave": { title: "Laumassa hautaan", copy: "Oli mukana yhteisessä harhassa ja keräsi illan eniten huteja.", reason: "Vähintään viiden pelaajan pelissä osallistui vähintään kolmen pelaajan yksimielisesti väärään ennustukseen ja sai ehdokkaista eniten ennustuksia väärin." },
		},
	},
	footer: "ÖRKKIPOKKA",
} as const;
